# VPN 路由自动化配置文件
# 修改后需要重启服务：launchctl kickstart -k gui/$(id -u)/com.user.vpn-route-automator

# VPN 连接名称（在系统设置 → 网络 中看到的名字）
VPN_NAME="Company VPN"

# VPN 网络接口名
VPN_INTERFACE="ppp0"

# VPN PID 文件路径
VPN_PID_FILE="/var/run/ppp0.pid"

# 需要添加的路由（数组格式）
ROUTES=(
"192.168.69.12/24"
"192.168.123.0/24"
"192.168.59.110"
"47.103.142.44"
"47.102.113.86"
"192.168.59.122"
)
