name: Xcode - Build and Analyze

on:
  push:
    branches: [ "main" ]
  # 不允许 PR 触发，防止恶意代码在你的机器上执行
  # pull_request:
  #   branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    name: Build and analyse
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: |
          # 调用本地构建脚本
          ~/actions-runner/build-scripts/route-pilot.sh